### PR TITLE
Add emojis to replace symbols, improve text & tidy

### PR DESCRIPTION
**Pull request by S33G**
- Add emoji's to replace old (missing) font awesome icons
- Tidy html
- Improve text in banking

### CODE REVIEW

**Review by Shinotama — APPROVED** [review]
Seems pretty decent, not sure 100% about the usage of Emojis vs FA assets.

**Comment by charj** [comment]
> 

Font awesome icons were not functional

**Comment by charj** [comment]
> Seems pretty decent, not sure 100% about the usage of Emojis vs FA assets.

Font awesome icons were not functional

**Comment by Shinotama** [comment]
> 

Yeah that makes sense, well perhaps they're just the wrong code, I was looking at that now, going to do a non-emoji variant for people as I'm doing a Fleeca bank overlay.

**Review by sinphoenix — APPROVED** [review]

**Review by sinphoenix — APPROVED** [review]

**Review by sinphoenix — APPROVED** [review]

**Comment by GhzGarage** [comment]
I've pushed a fix for the font awesome icons not showing

**Pull request closed without merging**
